FROM ubuntu:bionic
LABEL maintainer="Axe Developers <dev@axe.org>"
LABEL description="Dockerised AxeCore"

ARG USER_ID
ARG GROUP_ID
ARG TAG

ENV HOME /home/axe

# add user with specified (or default) user/group ids
ENV USER_ID ${USER_ID:-1000}
ENV GROUP_ID ${GROUP_ID:-1000}
RUN groupadd -g ${GROUP_ID} axe && \
    useradd -u ${USER_ID} -g axe -s /bin/bash -m -d /home/axe axe  && \
    mkdir /home/axe/.axecore && \
    chown ${USER_ID}:${GROUP_ID} -R /home/axe

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN mach=$(uname -m) \
      && case $mach in aarch64) arch="aarch64-linux-gnu"; ;; x86_64) arch="x86_64-linux-gnu"; ;;  *) echo "ERROR: Machine type $mach not supported."; ;; esac \
      && wget https://github.com/axerunners/axe/releases/download/v${TAG}/axecore-${TAG}-$arch.tar.gz -P /tmp \
      && tar -xvf /tmp/axecore-*.tar.gz -C /tmp/ \
      && cp /tmp/axecore*/bin/*  /usr/local/bin \
      && rm -rf /tmp/axecore* \
      && chmod a+x /usr/local/bin/*

USER axe

VOLUME ["/home/axe"]

COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 9337 9937 19337 19937

WORKDIR /home/axe
